package dicechess.bot;

import dicechess.engine.domain.FenParser;
import dicechess.engine.domain.GameState;
import dicechess.engine.search.TurnGenerator;

import lv.id.jc.dicechess.runtime.TurnContext;

import scala.collection.immutable.List;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.invoke.MethodType;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.util.ArrayList;
import java.util.Collections;

/**
 * Strategy implementation using an ONNX value model (or fallback engine evaluation)
 * over all legal full-turn paths generated by TurnGenerator.
 *
 * <p>TurnGenerator returns {@code List[List[Move]]} where {@code Move} is an opaque
 * Int with layout: bits 0-5 = destination (to), bits 6-11 = source (from),
 * bits 12-15 = flags.</p>
 */
public class OnnxStrategy implements Strategy {

    private static final Logger logger = System.getLogger(OnnxStrategy.class.getName());
    private static final MethodHandle MAKE_MOVE_MH;

    static {
        try {
            var clazz = Class.forName("dicechess.engine.domain.Position$package");
            var methodType = MethodType.methodType(GameState.class, GameState.class, int.class);
            MAKE_MOVE_MH = MethodHandles.lookup().findStatic(clazz, "makeMove_Move", methodType);
        } catch (Exception e) {
            throw new ExceptionInInitializerError(e);
        }
    }

    private final OnnxEvaluator evaluator;

    public OnnxStrategy(OnnxEvaluator evaluator) {
        this.evaluator = evaluator;
    }

    @Override
    public java.util.List<String> chooseMoves(TurnContext context) {
        if (context == null || context.dfen() == null || context.dfen().isBlank()) {
            logger.log(Level.WARNING, "Received empty or null DFEN context");
            return Collections.emptyList();
        }

        var parseResult = FenParser.parse(context.dfen());
        if (parseResult.isLeft()) {
            var errorMsg = parseResult.left().toOption().isDefined()
                    ? parseResult.left().toOption().get()
                    : "Unknown FEN error";
            logger.log(Level.ERROR, "Failed to parse DFEN ''{0}'': {1}", context.dfen(), errorMsg);
            return Collections.emptyList();
        }

        var initialState = parseResult.toOption().get();
        var activeColor = initialState.flags() & 1; // Bit 0 of flags is activeColor (0 = White, 1 = Black)

        // TurnGenerator returns List[List[Move]]
        @SuppressWarnings("unchecked")
        var legalTurnPaths =
                (List<List<Object>>) (Object) TurnGenerator.generateAllLegalTurnPaths(initialState);

        if (legalTurnPaths.isEmpty()) {
            logger.log(Level.INFO, "No legal turn paths available for DFEN: {0}", context.dfen());
            return Collections.emptyList();
        }

        java.util.List<Integer> bestPath = null;
        float bestScore = -Float.MAX_VALUE;

        for (var pathScala : scala.jdk.javaapi.CollectionConverters.asJava(legalTurnPaths)) {
            var pathJava = toJavaIntegerList(pathScala);

            // Apply sequence of Move values using makeMove_Move to get final turn state
            var currentState = initialState;
            for (var moveInt : pathJava) {
                currentState = applyMove(currentState, moveInt);
            }

            // Score final state from initial mover's perspective
            var score = evaluator.evaluate(currentState, activeColor);

            if (score > bestScore || bestPath == null) {
                bestScore = score;
                bestPath = pathJava;
            }
        }

        if (bestPath == null || bestPath.isEmpty()) {
            return Collections.emptyList();
        }

        var moveNotations = new ArrayList<String>();
        for (var moveInt : bestPath) {
            moveNotations.add(moveToNotation(moveInt));
        }

        logger.log(Level.DEBUG, "Chosen turn path: {0} with score {1}", moveNotations, bestScore);
        return moveNotations;
    }

    private static GameState applyMove(GameState state, int moveInt) {
        try {
            return (GameState) MAKE_MOVE_MH.invokeExact(state, moveInt);
        } catch (Throwable e) {
            throw new IllegalStateException("Failed to apply move via engine: " + moveInt, e);
        }
    }

    /**
     * Converts a packed Move int to long algebraic notation (e.g. "e2e4", "e7e8q").
     *
     * <p>Move layout (from Move.scala):
     * <ul>
     *     <li>Bits 0-5: destination square (to)</li>
     *     <li>Bits 6-11: source square (from)</li>
     *     <li>Bits 12-15: move flags</li>
     * </ul>
     */
    static String moveToNotation(int move) {
        var to = move & 0x3f;
        var from = (move >>> 6) & 0x3f;
        var flags = (move >>> 12) & 0x0f;

        var fromFile = (char) ('a' + (from % 8));
        var fromRank = (from / 8) + 1;
        var toFile = (char) ('a' + (to % 8));
        var toRank = (to / 8) + 1;

        // Promotion: flags bit 3 set (flags >= 8)
        var promStr = "";
        if ((flags & 8) != 0) {
            promStr = switch (flags & 3) {
                case 0 -> "n"; // KnightPromotion(8) or KnightPromoCapture(12)
                case 1 -> "b"; // BishopPromotion(9) or BishopPromoCapture(13)
                case 2 -> "r"; // RookPromotion(10) or RookPromoCapture(14)
                case 3 -> "q"; // QueenPromotion(11) or QueenPromoCapture(15)
                default -> "";
            };
        }

        return "" + fromFile + fromRank + toFile + toRank + promStr;
    }

    private static java.util.List<Integer> toJavaIntegerList(List<Object> scalaList) {
        var result = new ArrayList<Integer>();
        for (var item : scala.jdk.javaapi.CollectionConverters.asJava(scalaList)) {
            if (item instanceof Integer intValue) {
                result.add(intValue);
            } else if (item instanceof Number number) {
                result.add(number.intValue());
            }
        }
        return result;
    }
}
