package dicechess.bot;

import dicechess.engine.domain.FenParser;
import dicechess.engine.domain.GameState;
import dicechess.engine.domain.Position$package$;
import dicechess.engine.search.TurnGenerator;

import lv.id.jc.dicechess.runtime.TurnContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import scala.collection.immutable.List;

import java.util.ArrayList;
import java.util.Collections;

/**
 * Strategy implementation using an ONNX value model (or fallback engine evaluation)
 * over all legal full-turn paths generated by TurnGenerator.
 *
 * <p>TurnGenerator returns {@code List[List[Move]]} where {@code Move} is an opaque
 * Int with layout: bits 0-5 = destination (to), bits 6-11 = source (from),
 * bits 12-15 = flags.</p>
 */
public class OnnxStrategy implements Strategy {

    private static final Logger logger = LoggerFactory.getLogger(OnnxStrategy.class);

    private final OnnxEvaluator evaluator;

    public OnnxStrategy(OnnxEvaluator evaluator) {
        this.evaluator = evaluator;
    }

    @Override
    public java.util.List<String> chooseMoves(TurnContext context) {
        if (context == null || context.dfen() == null || context.dfen().isBlank()) {
            logger.warn("Received empty or null DFEN context");
            return Collections.emptyList();
        }

        var parseResult = FenParser.parse(context.dfen());
        if (parseResult.isLeft()) {
            String errorMsg = parseResult.left().toOption().isDefined()
                    ? parseResult.left().toOption().get()
                    : "Unknown FEN error";
            logger.error("Failed to parse DFEN '{}': {}", context.dfen(), errorMsg);
            return Collections.emptyList();
        }

        GameState initialState = parseResult.toOption().get();
        int activeColor = initialState.flags() & 1; // Bit 0 of flags is activeColor (0 = White, 1 = Black)

        // TurnGenerator returns List[List[Move]]
        @SuppressWarnings("unchecked")
        List<List<Object>> legalTurnPaths =
                (List<List<Object>>) (Object) TurnGenerator.generateAllLegalTurnPaths(initialState);

        if (legalTurnPaths.isEmpty()) {
            logger.info("No legal turn paths available for DFEN: {}", context.dfen());
            return Collections.emptyList();
        }

        java.util.List<Integer> bestPath = null;
        float bestScore = -Float.MAX_VALUE;

        for (List<Object> pathScala : scala.jdk.javaapi.CollectionConverters.asJava(legalTurnPaths)) {
            java.util.List<Integer> pathJava = toJavaIntegerList(pathScala);

            // Apply sequence of Move values using makeMove_Move to get final turn state
            GameState currentState = initialState;
            for (Integer moveInt : pathJava) {
                currentState = Position$package$.MODULE$.makeMove_Move(currentState, moveInt);
            }

            // Score final state from initial mover's perspective
            float score = evaluator.evaluate(currentState, activeColor);

            if (score > bestScore || bestPath == null) {
                bestScore = score;
                bestPath = pathJava;
            }
        }

        if (bestPath == null || bestPath.isEmpty()) {
            return Collections.emptyList();
        }

        java.util.List<String> moveNotations = new ArrayList<>();
        for (Integer moveInt : bestPath) {
            moveNotations.add(moveToNotation(moveInt));
        }

        logger.debug("Chosen turn path: {} with score {}", moveNotations, bestScore);
        return moveNotations;
    }

    /**
     * Converts a packed Move int to long algebraic notation (e.g. "e2e4", "e7e8q").
     *
     * <p>Move layout (from Move.scala):
     * <ul>
     *     <li>Bits 0-5: destination square (to)</li>
     *     <li>Bits 6-11: source square (from)</li>
     *     <li>Bits 12-15: move flags</li>
     * </ul>
     */
    static String moveToNotation(int move) {
        int to = move & 0x3f;
        int from = (move >>> 6) & 0x3f;
        int flags = (move >>> 12) & 0x0f;

        char fromFile = (char) ('a' + (from % 8));
        int fromRank = (from / 8) + 1;
        char toFile = (char) ('a' + (to % 8));
        int toRank = (to / 8) + 1;

        // Promotion: flags bit 3 set (flags >= 8)
        String promStr = "";
        if ((flags & 8) != 0) {
            promStr = switch (flags & 3) {
                case 0 -> "n"; // KnightPromotion(8) or KnightPromoCapture(12)
                case 1 -> "b"; // BishopPromotion(9) or BishopPromoCapture(13)
                case 2 -> "r"; // RookPromotion(10) or RookPromoCapture(14)
                case 3 -> "q"; // QueenPromotion(11) or QueenPromoCapture(15)
                default -> "";
            };
        }

        return "" + fromFile + fromRank + toFile + toRank + promStr;
    }

    private static java.util.List<Integer> toJavaIntegerList(List<Object> scalaList) {
        java.util.List<Integer> result = new ArrayList<>();
        for (Object item : scala.jdk.javaapi.CollectionConverters.asJava(scalaList)) {
            if (item instanceof Integer intValue) {
                result.add(intValue);
            } else if (item instanceof Number number) {
                result.add(number.intValue());
            }
        }
        return result;
    }
}
